namespace FluffyDisdog 
{
public enum ToolType
{
    None = -1,
    Shovel = 0 ,
    Rake = 1 ,
    CARD_Shovel_Enhanced = 2 ,
    CARD_Rake_Enhanced = 3 ,
    CARD_Golden_Shovel = 4 ,
    CARD_Golden_Shovel_Enhanced = 5 ,
    CARD_Axe = 6 ,
    CARD_Axe_Enhanced = 7 ,
    CARD_Cross = 8 ,
    CARD_Cross_Enhanced = 9 ,
    CARD_X_Blade = 10 ,
    CARD_X_Blade_Enhanced = 11 ,
    CARD_Random_Destruction = 12 ,
    CARD_Random_Destruction_Enhanced = 13 ,
    CARD_Block_X_Weakener = 14 ,
    CARD_Block_X_Weakener_Enhanced = 15 ,
    CARD_Block_Cross_Weakener = 16 ,
    CARD_Block_Cross_Weakener_Enhanced = 17 ,
    CARD_Golden_Axe = 18 ,
    CARD_Golden_Axe_Enhanced = 19 ,
    CARD_H_Beam = 20 ,
    CARD_H_Beam_Enhanced = 21 ,
    CARD_Weakening_Card_Normal = 22 ,
    CARD_Weakening_Card_Rare = 23 ,
    CARD_Weakening_Card_Unique = 24 ,
    CARD_Bag = 25 ,
    CARD_Tool_Modifier = 26 ,
    CARD_Tool_Enhancer = 27 ,
    NewTool27 = 28 ,
    NewTool28 = 29 ,
    NewTool29 = 30 ,
    NewTool30 = 31 ,
    NewTool31 = 32 ,
    NewTool32 = 33 ,
    NewTool33 = 34 ,
    NewTool34 = 35 ,
    NewTool35 = 36 ,
    NewTool36 = 37 ,
    NewTool37 = 38 ,
    NewTool38 = 39 ,
    NewTool39 = 40 ,
    NewTool40 = 41 ,
    NewTool41 = 42 ,
    NewTool42 = 43 ,
    NewTool43 = 44 ,
    NewTool44 = 45 ,
    NewTool45 = 46 ,
    NewTool46 = 47 ,
    NewTool47 = 48 ,
    NewTool48 = 49 ,
    NewTool49 = 50 ,
    MAX = 51,
}
}
