namespace FluffyDisdog 
{
public enum ToolType
{
    None = -1,
    Card_Shovel = 0 ,
    Card_Rake = 1 ,
    Card_Shovel_Enhanced = 2 ,
    Card_Rake_Enhanced = 3 ,
    Card_GoldenShovel = 4 ,
    Card_GoldenShovel_Enhanced = 5 ,
    Card_Axe = 6 ,
    Card_Axe_Enhanced = 7 ,
    Card_CrossChisel = 8 ,
    Card_CrossChisel_Enhanced = 9 ,
    Card_Pickaxe = 10 ,
    Card_Pickaxe_Enhanced = 11 ,
    Card_Slingshot = 12 ,
    Card_Slingshot_Enhanced = 13 ,
    Card_CornerCrushingHammer = 14 ,
    Card_CornerCrushingHammer_Enhanced = 15 ,
    Card_ConcentratedCrossDrill = 16 ,
    Card_ConcentratedCrossDrill_Enhanced = 17 ,
    Card_GoldenAxe = 18 ,
    Card_GoldenAxe_Enhanced = 19 ,
    Card_LargeScissors = 20 ,
    Card_LargeScissors_Enhanced = 21 ,
    Card_WeakeningNormal = 22 ,
    Card_WeakeningRare = 23 ,
    Card_WeakeningUnique = 24 ,
    Card_Bag = 25 ,
    Card_ToolTransformation = 26 ,
    Card_ToolEnhancement = 27 ,
    Card_AdventurerTorch = 28 ,
    Card_AdventurerTorch_Enhanced = 29 ,
    Card_HammerOfMemory = 30 ,
    Card_HammerOfMemory_Enhanced = 31 ,
    Card_RiftStartumAnalysis = 32 ,
    Card_RiftStartumAnalysis_Enhanced = 33 ,
    NewValue = 34 ,
    MAX = 35,
}
}
